[package]
name = "spider"
version = "0.0.8"
edition = "2021"

[dependencies]
anyhow = "1.0"
async-channel = "2.3.1"
async-iterator = "2.3.0"
dircpy = "0.3.19"
futures = "0.3.30"
gettext-rs = { version = "0.7", features = ["gettext-system"] }
glycin = { version = "3", features = ["gdk4"] }
isahc = "1.8.2"
lazy_static = "1.5.0"
open = "5.3.5"
rand = "0.8.5"
scraper = { version = "0.27.0", features = ["atomic"] }
url = "2.5.8"

[dependencies.ashpd]
package = "ashpd"
version = "0.13.11"
features = ["async-io", "gtk4", "dynamic_launcher"]
default-features = false

[dependencies.gtk]
package = "gtk4"
version = "0.11"
features = ["v4_22"]

[dependencies.adw]
package = "libadwaita"
version = "0.9"
features = ["v1_9"]

[dependencies.webkit]
package = "webkit6"
version = "0.6"
features = ["v2_52"]
